# Welcome to Jekyll!

# Website settings
title: "hanay"
description: "Hanay's blog,use Jekyll and github pages."
keywords: "Hanay,hanay,blog,Jekyll,github,gh-pages"
baseurl: "/"
url: "http://hanay.space"
# url: "http://127.0.0.1:4000"

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'

# author
author:
  name: 'hanay'
  first_name: 'haihong'
  last_name: 'Lee'
  email: '1114709480@qq.com'
  facebook_username: 'hanayzZ'
  github_username: 'hanayzZ'
  head_img: 'static/img/landing/hanay.JPG'

# social link
jingyu:
  first_name: 'haihong'
  last_name: 'Lee'
  description: 'Painter.'
  link: 'http://angular.jack003.com'
  email: '1114709480@qq.com'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Skills'
  projects: 'Project'
  blog: 'Blog'
  link: 'Link'

# my projects
project:
  saplatform:
    name: 'tidyWebsite'
    url: 'https://www.24tidy.com'
    img: 'static/img/landing/saplatform.png'
  jalpc:
    name: 'wandabox'
    url: 'http://wandabox.24tidy.com/'
    img: 'static/img/landing/jekyll.png'
  angularjs:
    name: 'tidyWebApp'
    url: 'https://m.24tidy.com'
    img: 'static/img/landing/angularjs.png'
  Rsser:
    name: 'monthLottery'
    url: 'https://m.24tidy.com/activity/monthLottery/tpl/8/index.html'
    img: 'static/img/landing/rsser.png'

# blog index
index:
  home: 'Home'
  html: 'HTML'
  css: 'Css'
  javaScript: 'JavaScript'
  jQuery: 'JQuery'
  angularJs: 'AngularJs'
  vueJs: 'VueJs'
  reactJs: 'ReactJs'
  other: 'Other'
  life: 'Life'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
